caddy_install_path: /usr/local/bin/caddy
caddy_config_dir: /etc/caddy
caddy_data_dir: /var/lib/caddy
caddy_log_dir: /var/log/caddy
caddy_user: caddy
caddy_group: caddy
caddy_cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
caddy_acme_email: ""
caddy_domain: internal.thespragg.dev
caddy_proxies: []
