all:
  children:
    bots:
      hosts:
        osrs-clan-bot:
          ansible_host: 10.10.0.21
          ansible_user: root
    databases:
      hosts:
        postgres:
          ansible_host: 10.10.0.22
          ansible_user: root