all:
  children:
    proxmox:
      hosts:
        apollo:
          ansible_host: apollo.internal.thespragg.dev
          ansible_user: root
    bots:
      hosts:
        osrs-clan-bot:
          ansible_host: 10.10.0.21
          ansible_user: root
    databases:
      hosts:
        postgres:
          ansible_host: 10.10.0.22
          ansible_user: root
    monitoring:
      hosts:
        grafana:
          ansible_host: 10.10.0.23
          ansible_user: root
    proxy:
      hosts:
        caddy:
          ansible_host: 10.10.0.24
          ansible_user: root