- name: Read local storage configuration
  command: "grep -A5 '^dir: local' /etc/pve/storage.cfg"
  register: local_storage_config
  changed_when: false

- name: Enable import content type on local storage
  command: pvesm set local --content iso,vztmpl,backup,import
  when: "'import' not in local_storage_config.stdout"
