adguard_upstream_dns:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8

adguard_rewrites:
  - domain: "apollo.host.internal.thespragg.dev"
    answer: "10.0.10.2"
  - domain: "adguard.host.internal.thespragg.dev"
    answer: "10.0.40.3"
  - domain: "caddy.host.internal.thespragg.dev"
    answer: "10.0.40.4"
  - domain: "unifi.host.internal.thespragg.dev"
    answer: "10.0.40.5"
  - domain: "osrs-clan-bot.host.internal.thespragg.dev"
    answer: "10.0.40.6"
  - domain: "postgres.host.internal.thespragg.dev"
    answer: "10.0.40.7"
  - domain: "grafana.host.internal.thespragg.dev"
    answer: "10.0.40.8"
  - domain: "paperless.host.internal.thespragg.dev"
    answer: "10.0.40.9"
  - domain: "titan.host.internal.thespragg.dev"
    answer: "10.0.40.200"
  - domain: "apollo.internal.thespragg.dev"
    answer: "10.0.40.4"
  - domain: "grafana.internal.thespragg.dev"
    answer: "10.0.40.4"
  - domain: "unifi.internal.thespragg.dev"
    answer: "10.0.40.4"
  - domain: "paperless.internal.thespragg.dev"
    answer: "10.0.40.4"
  - domain: "adguard.internal.thespragg.dev"
    answer: "10.0.40.4"
  - domain: "titan.internal.thespragg.dev"
    answer: "10.0.40.4"
  - domain: "immich.internal.thespragg.dev"
    answer: "10.0.40.4"
  - domain: "router.internal.thespragg.dev"
    answer: "10.0.40.4"

adguard_user_rules:
  - "||router.host.internal.thespragg.dev^$client=10.0.10.0/24,dnstype=A,dnsrewrite=NOERROR;A;10.0.10.1"
  - "||router.host.internal.thespragg.dev^$client=10.0.20.0/24,dnstype=A,dnsrewrite=NOERROR;A;10.0.20.1"
  - "||router.host.internal.thespragg.dev^$client=10.0.30.0/24,dnstype=A,dnsrewrite=NOERROR;A;10.0.30.1"
  - "||router.host.internal.thespragg.dev^$client=10.0.40.0/24,dnstype=A,dnsrewrite=NOERROR;A;10.0.40.1"
  - "||router.host.internal.thespragg.dev^$client=10.0.50.0/24,dnstype=A,dnsrewrite=NOERROR;A;10.0.50.1"
