postgres_allowed_hosts:
  - 10.10.0.21
  - 10.0.40.30

postgres_databases:
  - name: osrs_clan_bot
    user: osrs_clan_bot_user
    password: "{{ vault_osrs_clan_bot_db_password }}"
  - name: paperless
    user: paperless_user
    password: "{{ vault_paperless_db_password }}"

restic_jobs:
  - name: osrs-clan-bot
    type: postgres
    database: osrs_clan_bot
    db_user: osrs_clan_bot_user
    db_password: "{{ vault_osrs_clan_bot_db_password }}"
    schedule: daily
    retention:
      daily: 7
      weekly: 4
      monthly: 6
  - name: paperless
    type: postgres
    database: paperless
    db_user: paperless_user
    db_password: "{{ vault_paperless_db_password }}"
    schedule: daily
    retention:
      daily: 14
      weekly: 8
      monthly: 12
