immich_dir: /opt/immich
immich_version: release
immich_bind_address: 10.0.40.200
immich_port: 2283
immich_allowed_hosts:
  - 10.0.40.0/24
immich_upload_location: /data/immich
immich_db_data_location: /data/immich/postgres
immich_db_name: immich
immich_db_username: postgres
immich_db_password: "lk5A9bR2xT7vQ4mN8pZ3sY6cD1fH0jK"
